# Generated by Django 4.1.7 on 2023-04-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lttr', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='updated_at',
        ),
    ]
