# Generated by Django 4.1.7 on 2023-03-03 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lttr', '0002_alter_letter_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
